version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "System.Configuration.ConfigurationManager"
      - dependency-name: "System.Threading.Tasks.Extensions"
    groups:
      xunit:
        patterns:
          - "xunit*"
          - "Verify*"
      mstest:
        patterns:
          - "MSTest*"
      nuke:
        patterns:
          - "Nuke*"
      nunit:
        patterns:
          - "NUnit*"
